server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petwaale
    username: root
    password: Aniket123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_email_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

auth:
  service:
    url: http://localhost:8080/api/auth
